INSERT INTO relacional.CATEGORIA(nome) VALUES('LIVROS');
INSERT INTO relacional.CATEGORIA(nome) VALUES('DVDS');
INSERT INTO relacional.CATEGORIA(nome) VALUES('GAMES');
INSERT INTO relacional.CATEGORIA(nome) VALUES('CELULARES');
INSERT INTO relacional.CATEGORIA(nome) VALUES('INFORMATICA');
INSERT INTO relacional.CATEGORIA(nome) VALUES('TV E AUDIO');
INSERT INTO relacional.CATEGORIA(nome) VALUES('ELETRODOMESTICOS');
INSERT INTO relacional.CATEGORIA(nome) VALUES('MOVEIS');
INSERT INTO relacional.CATEGORIA(nome) VALUES('PASSAGENS');