CREATE SCHEMA relacional;


CREATE TABLE relacional.CLIENTE(
    IDCLIENTE SERIAL primary key,
    NOME VARCHAR(30) NOT NULL,
    SOBRENOME VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(60) NOT NULL,
    SEXO CHAR(1) NOT NULL,
    NASCIMENTO DATE NOT NULL
);	


CREATE TABLE relacional.ENDERECO(
    IDENDERECO SERIAL PRIMARY key,
    RUA VARCHAR(100) NOT NULL,
    CIDADE VARCHAR(50) NOT NULL,
    ESTADO VARCHAR(20) NOT NULL,
    REGIAO VARCHAR(20) NOT NULL,
    ID_CLIENTE INT UNIQUE
);

CREATE TABLE relacional.VENDEDOR(
    IDVENDEDOR SERIAL PRIMARY key,
    NOME VARCHAR(30) NOT NULL,
    SEXO CHAR(1) NOT NULL,
    EMAIL VARCHAR(30) NOT NULL,
    ID_GERENTE INT
);

CREATE TABLE relacional.CATEGORIA(
    IDCATEGORIA SERIAL PRIMARY key,
    NOME VARCHAR(30) NOT NULL
);

CREATE TABLE relacional.FORNECEDOR(
    IDFORNECEDOR SERIAL PRIMARY key,
    NOME VARCHAR(50) NOT NULL
);


CREATE TABLE relacional.PRODUTO(
    IDPRODUTO SERIAL PRIMARY key,
    PRODUTO VARCHAR(100) NOT NULL,
    VALOR NUMERIC(10,2) NOT NULL,
    CUSTO_MEDIO NUMERIC(10,2),
    ID_CATEGORIA INT,
    ID_FORNECEDOR INT
);

CREATE TABLE relacional.FORMA_PAGAMENTO(
    IDFORMA SERIAL PRIMARY key,
    FORMA VARCHAR(40) NOT NULL
);

CREATE TABLE relacional.ITEM_NOTA(
    IDITEMNOTA SERIAL PRIMARY key,
    ID_PRODUTO INT,
    ID_NOTA_FISCAL INT,
    QUANTIDADE INT,
    TOTAL NUMERIC(10,2)	
);

CREATE TABLE relacional.NOTA_FISCAL(
    IDNOTA SERIAL PRIMARY key,
    DATA DATE,
    TOTAL NUMERIC(10,2),
    ID_FORMA INT,
    ID_CLIENTE INT,
    ID_VENDEDOR INT
);